ALTER TABLE plans ADD COLUMN phone TEXT;
ALTER TABLE plans ADD COLUMN paid INTEGER NOT NULL DEFAULT 0;
ALTER TABLE plans ADD COLUMN amount TEXT;
ALTER TABLE plans ADD COLUMN pay_via TEXT;
ALTER TABLE plans ADD COLUMN scope TEXT NOT NULL DEFAULT 'bundle';
ALTER TABLE plans ADD COLUMN created TEXT;
