CREATE TABLE IF NOT EXISTS progress (
  email          TEXT NOT NULL,
  device         TEXT NOT NULL,
  child_hash     TEXT NOT NULL,
  child_name     TEXT,
  level          INTEGER DEFAULT 1,
  xp             INTEGER DEFAULT 0,
  stars          INTEGER DEFAULT 0,
  streak         INTEGER DEFAULT 0,
  accuracy       INTEGER DEFAULT 0,
  asked          INTEGER DEFAULT 0,
  correct        INTEGER DEFAULT 0,
  areas_json     TEXT,
  weak_json      TEXT,
  badges         INTEGER DEFAULT 0,
  last_practised TEXT,
  app_version    TEXT,
  updated        TEXT,
  PRIMARY KEY (email, device, child_hash)
);
CREATE TABLE IF NOT EXISTS submissions (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  kind        TEXT NOT NULL,
  created     TEXT NOT NULL,
  status      TEXT NOT NULL DEFAULT 'pending',
  resolved    TEXT,
  app_version TEXT,
  device      TEXT,
  email       TEXT,
  lang        TEXT,
  item_kind   TEXT,
  item_id     TEXT,
  item_name   TEXT,
  field       TEXT,
  text        TEXT,
  note        TEXT
);
