/* Curated Bangla (bn) names for UN-member countries and their capitals.
   mledoze/countries has no Bengali translation, so these are hand-written in
   standard Bangladeshi usage (as seen in Bengali Wikipedia / national curriculum).
   Kids' geography tends to map to the 7-continent model, which is why the
   Americas are one region here. */

export const REGION_BN = {
  Asia: "এশিয়া",
  Africa: "আফ্রিকা",
  Europe: "ইউরোপ",
  Americas: "আমেরিকা",
  Oceania: "ওশেনিয়া",
  Antarctic: "অ্যান্টার্কটিকা",
};

/* cca3: [ English name, Bangla name, English capital, Bangla capital ] */
export const COUNTRY_BN = {
  AFG: ["Afghanistan", "আফগানিস্তান", "Kabul", "কাবুল"],
  ALB: ["Albania", "আলবেনিয়া", "Tirana", "তিরানা"],
  DZA: ["Algeria", "আলজেরিয়া", "Algiers", "আলজিয়ার্স"],
  AND: ["Andorra", "অ্যান্ডোরা", "Andorra la Vella", "অ্যান্ডোরা লা ভেলা"],
  AGO: ["Angola", "অ্যাঙ্গোলা", "Luanda", "লুয়ান্ডা"],
  ATG: ["Antigua and Barbuda", "অ্যান্টিগুয়া ও বারবুডা", "Saint John's", "সেন্ট জন'স"],
  ARG: ["Argentina", "আর্জেন্টিনা", "Buenos Aires", "বুয়েনস আইরেস"],
  ARM: ["Armenia", "আর্মেনিয়া", "Yerevan", "ইয়েরেভান"],
  AUS: ["Australia", "অস্ট্রেলিয়া", "Canberra", "ক্যানবেরা"],
  AUT: ["Austria", "অস্ট্রিয়া", "Vienna", "ভিয়েনা"],
  AZE: ["Azerbaijan", "আজারবাইজান", "Baku", "বাকু"],
  BHS: ["Bahamas", "বাহামা", "Nassau", "নাসাউ"],
  BHR: ["Bahrain", "বাহরাইন", "Manama", "মানামা"],
  BGD: ["Bangladesh", "বাংলাদেশ", "Dhaka", "ঢাকা"],
  BRB: ["Barbados", "বার্বাডোস", "Bridgetown", "ব্রিজটাউন"],
  BLR: ["Belarus", "বেলারুশ", "Minsk", "মিনস্ক"],
  BEL: ["Belgium", "বেলজিয়াম", "Brussels", "ব্রাসেলস"],
  BLZ: ["Belize", "বেলিজ", "Belmopan", "বেলমোপান"],
  BEN: ["Benin", "বেনিন", "Porto-Novo", "পোর্টো-নভো"],
  BTN: ["Bhutan", "ভুটান", "Thimphu", "থিম্পু"],
  BOL: ["Bolivia", "বলিভিয়া", "Sucre", "সুক্রে"],
  BIH: ["Bosnia and Herzegovina", "বসনিয়া ও হার্জেগোভিনা", "Sarajevo", "সারায়েভো"],
  BWA: ["Botswana", "বতসোয়ানা", "Gaborone", "গাবোরোন"],
  BRA: ["Brazil", "ব্রাজিল", "Brasília", "ব্রাসিলিয়া"],
  BRN: ["Brunei", "ব্রুনাই", "Bandar Seri Begawan", "বন্দর সেরি বেগাওয়ান"],
  BGR: ["Bulgaria", "বুলগেরিয়া", "Sofia", "সোফিয়া"],
  BFA: ["Burkina Faso", "বুরকিনা ফাসো", "Ouagadougou", "ওয়াগাদুগু"],
  BDI: ["Burundi", "বুরুন্ডি", "Gitega", "গিতেগা"],
  KHM: ["Cambodia", "কম্বোডিয়া", "Phnom Penh", "নম পেন"],
  CMR: ["Cameroon", "ক্যামেরুন", "Yaoundé", "ইয়াউন্ডে"],
  CAN: ["Canada", "কানাডা", "Ottawa", "অটোয়া"],
  CPV: ["Cape Verde", "কেপ ভার্দে", "Praia", "প্রাইয়া"],
  CAF: ["Central African Republic", "মধ্য আফ্রিকান প্রজাতন্ত্র", "Bangui", "বাঙ্গি"],
  TCD: ["Chad", "চাদ", "N'Djamena", "এনজামেনা"],
  CHL: ["Chile", "চিলি", "Santiago", "সান্টিয়াগো"],
  CHN: ["China", "চীন", "Beijing", "বেইজিং"],
  COL: ["Colombia", "কলম্বিয়া", "Bogotá", "বোগোতা"],
  COM: ["Comoros", "কোমোরোস", "Moroni", "মোরোনি"],
  COG: ["Congo", "কঙ্গো", "Brazzaville", "ব্রাজাভিল"],
  CRI: ["Costa Rica", "কোস্টা রিকা", "San José", "সান হোসে"],
  HRV: ["Croatia", "ক্রোয়েশিয়া", "Zagreb", "জাগ্রেব"],
  CUB: ["Cuba", "কিউবা", "Havana", "হাভানা"],
  CYP: ["Cyprus", "সাইপ্রাস", "Nicosia", "নিকোশিয়া"],
  CZE: ["Czechia", "চেক প্রজাতন্ত্র", "Prague", "প্রাগ"],
  DNK: ["Denmark", "ডেনমার্ক", "Copenhagen", "কোপেনহেগেন"],
  DJI: ["Djibouti", "জিবুতি", "Djibouti", "জিবুতি"],
  DMA: ["Dominica", "ডোমিনিকা", "Roseau", "রোজো"],
  DOM: ["Dominican Republic", "ডোমিনিকান প্রজাতন্ত্র", "Santo Domingo", "সান্টো ডোমিঙ্গো"],
  COD: ["DR Congo", "গণতান্ত্রিক কঙ্গো প্রজাতন্ত্র", "Kinshasa", "কিনশাসা"],
  ECU: ["Ecuador", "ইকুয়েডর", "Quito", "কিতো"],
  EGY: ["Egypt", "মিশর", "Cairo", "কায়রো"],
  SLV: ["El Salvador", "এল সালভাদর", "San Salvador", "সান সালভাদর"],
  GNQ: ["Equatorial Guinea", "নিরক্ষীয় গিনি", "Malabo", "মালাবো"],
  ERI: ["Eritrea", "ইরিত্রিয়া", "Asmara", "আসমারা"],
  EST: ["Estonia", "এস্তোনিয়া", "Tallinn", "তালিন"],
  SWZ: ["Eswatini", "ইসওয়াতিনি", "Lobamba", "লোবাম্বা"],
  ETH: ["Ethiopia", "ইথিওপিয়া", "Addis Ababa", "আদ্দিস আবাবা"],
  FJI: ["Fiji", "ফিজি", "Suva", "সুভা"],
  FIN: ["Finland", "ফিনল্যান্ড", "Helsinki", "হেলসিংকি"],
  FRA: ["France", "ফ্রান্স", "Paris", "প্যারিস"],
  GAB: ["Gabon", "গ্যাবন", "Libreville", "লিব্রেভিল"],
  GMB: ["Gambia", "গাম্বিয়া", "Banjul", "বাঞ্জুল"],
  GEO: ["Georgia", "জর্জিয়া", "Tbilisi", "তিবিলিসি"],
  DEU: ["Germany", "জার্মানি", "Berlin", "বার্লিন"],
  GHA: ["Ghana", "ঘানা", "Accra", "আক্রা"],
  GRC: ["Greece", "গ্রিস", "Athens", "অ্যাথেন্স"],
  GRD: ["Grenada", "গ্রেনাডা", "St. George's", "সেন্ট জর্জ'স"],
  GTM: ["Guatemala", "গুয়াতেমালা", "Guatemala City", "গুয়াতেমালা সিটি"],
  GIN: ["Guinea", "গিনি", "Conakry", "কোনাক্রি"],
  GNB: ["Guinea-Bissau", "গিনি-বিসাউ", "Bissau", "বিসাউ"],
  GUY: ["Guyana", "গায়ানা", "Georgetown", "জর্জটাউন"],
  HTI: ["Haiti", "হাইতি", "Port-au-Prince", "পোর্ট-অ-প্রিন্স"],
  HND: ["Honduras", "হন্ডুরাস", "Tegucigalpa", "তেগুসিগালপা"],
  HUN: ["Hungary", "হাঙ্গেরি", "Budapest", "বুদাপেস্ট"],
  ISL: ["Iceland", "আইসল্যান্ড", "Reykjavik", "রেইকিয়াভিক"],
  IND: ["India", "ভারত", "New Delhi", "নয়াদিল্লি"],
  IDN: ["Indonesia", "ইন্দোনেশিয়া", "Jakarta", "জাকার্তা"],
  IRN: ["Iran", "ইরান", "Tehran", "তেহরান"],
  IRQ: ["Iraq", "ইরাক", "Baghdad", "বাগদাদ"],
  IRL: ["Ireland", "আয়ারল্যান্ড", "Dublin", "ডাবলিন"],
  ISR: ["Israel", "ইসরায়েল", "Jerusalem", "জেরুসালেম"],
  ITA: ["Italy", "ইতালি", "Rome", "রোম"],
  CIV: ["Ivory Coast", "আইভরি কোস্ট", "Yamoussoukro", "ইয়ামুসুক্রো"],
  JAM: ["Jamaica", "জ্যামাইকা", "Kingston", "কিংস্টন"],
  JPN: ["Japan", "জাপান", "Tokyo", "টোকিও"],
  JOR: ["Jordan", "জর্ডান", "Amman", "আম্মান"],
  KAZ: ["Kazakhstan", "কাজাখস্তান", "Astana", "আস্তানা"],
  KEN: ["Kenya", "কেনিয়া", "Nairobi", "নাইরোবি"],
  KIR: ["Kiribati", "কিরিবাস", "South Tarawa", "দক্ষিণ তারাওয়া"],
  KWT: ["Kuwait", "কুয়েত", "Kuwait City", "কুয়েত সিটি"],
  KGZ: ["Kyrgyzstan", "কিরগিজস্তান", "Bishkek", "বিশকেক"],
  LAO: ["Laos", "লাওস", "Vientiane", "ভিয়েনতিয়েন"],
  LVA: ["Latvia", "লাটভিয়া", "Riga", "রিগা"],
  LBN: ["Lebanon", "লেবানন", "Beirut", "বৈরুত"],
  LSO: ["Lesotho", "লেসোথো", "Maseru", "মাসেরু"],
  LBR: ["Liberia", "লাইবেরিয়া", "Monrovia", "মনরোভিয়া"],
  LBY: ["Libya", "লিবিয়া", "Tripoli", "ত্রিপোলি"],
  LIE: ["Liechtenstein", "লিশটেনস্টাইন", "Vaduz", "ভাদুজ"],
  LTU: ["Lithuania", "লিথুয়ানিয়া", "Vilnius", "ভিলনিয়াস"],
  LUX: ["Luxembourg", "লুক্সেমবার্গ", "Luxembourg", "লুক্সেমবার্গ"],
  MDG: ["Madagascar", "মাদাগাস্কার", "Antananarivo", "আন্তানানারিভো"],
  MWI: ["Malawi", "মালাউই", "Lilongwe", "লিলংওয়ে"],
  MYS: ["Malaysia", "মালয়েশিয়া", "Kuala Lumpur", "কুয়ালালামপুর"],
  MDV: ["Maldives", "মালদ্বীপ", "Malé", "মালে"],
  MLI: ["Mali", "মালি", "Bamako", "বামাকো"],
  MLT: ["Malta", "মাল্টা", "Valletta", "ভ্যালেটা"],
  MHL: ["Marshall Islands", "মার্শাল দ্বীপপুঞ্জ", "Majuro", "মাজুরো"],
  MRT: ["Mauritania", "মৌরিতানিয়া", "Nouakchott", "নুয়াকশত"],
  MUS: ["Mauritius", "মরিশাস", "Port Louis", "পোর্ট লুইস"],
  MEX: ["Mexico", "মেক্সিকো", "Mexico City", "মেক্সিকো সিটি"],
  FSM: ["Micronesia", "মাইক্রোনেশিয়া", "Palikir", "পালিকির"],
  MDA: ["Moldova", "মলডোভা", "Chișinău", "কিশিনাউ"],
  MCO: ["Monaco", "মোনাকো", "Monaco", "মোনাকো"],
  MNG: ["Mongolia", "মঙ্গোলিয়া", "Ulan Bator", "উলানবাটর"],
  MNE: ["Montenegro", "মন্টিনিগ্রো", "Podgorica", "পডগোরিৎসা"],
  MAR: ["Morocco", "মরক্কো", "Rabat", "রাবাত"],
  MOZ: ["Mozambique", "মোজাম্বিক", "Maputo", "মাপুতো"],
  MMR: ["Myanmar", "মিয়ানমার", "Naypyidaw", "নাইপিদো"],
  NAM: ["Namibia", "নামিবিয়া", "Windhoek", "ভিন্টহুক"],
  NRU: ["Nauru", "নাউরু", "Yaren", "ইয়ারেন"],
  NPL: ["Nepal", "নেপাল", "Kathmandu", "কাঠমান্ডু"],
  NLD: ["Netherlands", "নেদারল্যান্ডস", "Amsterdam", "আমস্টারডাম"],
  NZL: ["New Zealand", "নিউজিল্যান্ড", "Wellington", "ওয়েলিংটন"],
  NIC: ["Nicaragua", "নিকারাগুয়া", "Managua", "মানাগুয়া"],
  NER: ["Niger", "নাইজার", "Niamey", "নিয়ামে"],
  NGA: ["Nigeria", "নাইজেরিয়া", "Abuja", "আবুজা"],
  PRK: ["North Korea", "উত্তর কোরিয়া", "Pyongyang", "পিয়ংইয়ং"],
  MKD: ["North Macedonia", "উত্তর ম্যাসেডোনিয়া", "Skopje", "স্কোপিয়ে"],
  NOR: ["Norway", "নরওয়ে", "Oslo", "অসলো"],
  OMN: ["Oman", "ওমান", "Muscat", "মাস্কাট"],
  PAK: ["Pakistan", "পাকিস্তান", "Islamabad", "ইসলামাবাদ"],
  PLW: ["Palau", "পালাউ", "Ngerulmud", "এনগেরুলমুদ"],
  PAN: ["Panama", "পানামা", "Panama City", "পানামা সিটি"],
  PNG: ["Papua New Guinea", "পাপুয়া নিউগিনি", "Port Moresby", "পোর্ট মোর্সবি"],
  PRY: ["Paraguay", "প্যারাগুয়ে", "Asunción", "আসুনসিওন"],
  PER: ["Peru", "পেরু", "Lima", "লিমা"],
  PHL: ["Philippines", "ফিলিপাইন", "Manila", "ম্যানিলা"],
  POL: ["Poland", "পোল্যান্ড", "Warsaw", "ওয়ারশ"],
  PRT: ["Portugal", "পর্তুগাল", "Lisbon", "লিসবন"],
  QAT: ["Qatar", "কাতার", "Doha", "দোহা"],
  ROU: ["Romania", "রোমানিয়া", "Bucharest", "বুখারেস্ট"],
  RUS: ["Russia", "রাশিয়া", "Moscow", "মস্কো"],
  RWA: ["Rwanda", "রুয়ান্ডা", "Kigali", "কিগালি"],
  KNA: ["Saint Kitts and Nevis", "সেন্ট কিটস ও নেভিস", "Basseterre", "বাসেতের"],
  LCA: ["Saint Lucia", "সেন্ট লুসিয়া", "Castries", "ক্যাস্ট্রিস"],
  VCT: ["Saint Vincent and the Grenadines", "সেন্ট ভিনসেন্ট ও গ্রেনাডাইন", "Kingstown", "কিংস্টাউন"],
  WSM: ["Samoa", "সামোয়া", "Apia", "আপিয়া"],
  SMR: ["San Marino", "সান মারিনো", "City of San Marino", "সান মারিনো শহর"],
  STP: ["São Tomé and Príncipe", "সাও টোমে ও প্রিন্সিপে", "São Tomé", "সাও টোমে"],
  SAU: ["Saudi Arabia", "সৌদি আরব", "Riyadh", "রিয়াদ"],
  SEN: ["Senegal", "সেনেগাল", "Dakar", "ডাকার"],
  SRB: ["Serbia", "সার্বিয়া", "Belgrade", "বেলগ্রেড"],
  SYC: ["Seychelles", "সেশেলস", "Victoria", "ভিক্টোরিয়া"],
  SLE: ["Sierra Leone", "সিয়েরা লিওন", "Freetown", "ফ্রিটাউন"],
  SGP: ["Singapore", "সিঙ্গাপুর", "Singapore", "সিঙ্গাপুর"],
  SVK: ["Slovakia", "স্লোভাকিয়া", "Bratislava", "ব্রাতিস্লাভা"],
  SVN: ["Slovenia", "স্লোভেনিয়া", "Ljubljana", "লুব্লিয়ানা"],
  SLB: ["Solomon Islands", "সলোমন দ্বীপপুঞ্জ", "Honiara", "হোনিয়ারা"],
  SOM: ["Somalia", "সোমালিয়া", "Mogadishu", "মোগাদিশু"],
  ZAF: ["South Africa", "দক্ষিণ আফ্রিকা", "Pretoria", "প্রিটোরিয়া"],
  KOR: ["South Korea", "দক্ষিণ কোরিয়া", "Seoul", "সিউল"],
  SSD: ["South Sudan", "দক্ষিণ সুদান", "Juba", "জুবা"],
  ESP: ["Spain", "স্পেন", "Madrid", "মাদ্রিদ"],
  LKA: ["Sri Lanka", "শ্রীলঙ্কা", "Colombo", "কলম্বো"],
  SDN: ["Sudan", "সুদান", "Khartoum", "খার্তুম"],
  SUR: ["Suriname", "সুরিনাম", "Paramaribo", "পারামারিবো"],
  SWE: ["Sweden", "সুইডেন", "Stockholm", "স্টকহোম"],
  CHE: ["Switzerland", "সুইজারল্যান্ড", "Bern", "বার্ন"],
  SYR: ["Syria", "সিরিয়া", "Damascus", "দামেস্ক"],
  TJK: ["Tajikistan", "তাজিকিস্তান", "Dushanbe", "দুশানবে"],
  TZA: ["Tanzania", "তানজানিয়া", "Dodoma", "দোদোমা"],
  THA: ["Thailand", "থাইল্যান্ড", "Bangkok", "ব্যাংকক"],
  TLS: ["Timor-Leste", "পূর্ব তিমুর", "Dili", "দিলি"],
  TGO: ["Togo", "টোগো", "Lomé", "লোমে"],
  TON: ["Tonga", "টোঙ্গা", "Nuku'alofa", "নুকুয়ালোফা"],
  TTO: ["Trinidad and Tobago", "ত্রিনিদাদ ও টোবাগো", "Port of Spain", "পোর্ট অব স্পেন"],
  TUN: ["Tunisia", "তিউনিসিয়া", "Tunis", "তিউনিস"],
  TUR: ["Türkiye", "তুরস্ক", "Ankara", "আঙ্কারা"],
  TKM: ["Turkmenistan", "তুর্কমেনিস্তান", "Ashgabat", "আশগাবাত"],
  TUV: ["Tuvalu", "টুভালু", "Funafuti", "ফুনাফুতি"],
  UGA: ["Uganda", "উগান্ডা", "Kampala", "কাম্পালা"],
  UKR: ["Ukraine", "ইউক্রেন", "Kyiv", "কিয়েভ"],
  ARE: ["United Arab Emirates", "সংযুক্ত আরব আমিরাত", "Abu Dhabi", "আবুধাবি"],
  GBR: ["United Kingdom", "যুক্তরাজ্য", "London", "লন্ডন"],
  USA: ["United States", "মার্কিন যুক্তরাষ্ট্র", "Washington D.C.", "ওয়াশিংটন ডি.সি."],
  URY: ["Uruguay", "উরুগুয়ে", "Montevideo", "মন্টেভিডিও"],
  UZB: ["Uzbekistan", "উজবেকিস্তান", "Tashkent", "তাশখন্দ"],
  VUT: ["Vanuatu", "ভানুয়াতু", "Port Vila", "পোর্ট ভিলা"],
  VAT: ["Vatican City", "ভ্যাটিকান সিটি", "Vatican City", "ভ্যাটিকান সিটি"],
  VEN: ["Venezuela", "ভেনেজুয়েলা", "Caracas", "কারাকাস"],
  VNM: ["Vietnam", "ভিয়েতনাম", "Hanoi", "হ্যানয়"],
  YEM: ["Yemen", "ইয়েমেন", "Sana'a", "সানা"],
  ZMB: ["Zambia", "জাম্বিয়া", "Lusaka", "লুসাকা"],
  ZWE: ["Zimbabwe", "জিম্বাবুয়ে", "Harare", "হারারে"],
};
