/* Assemble geo-data.js from all source data.
   Run last in the build pipeline (`npm run data`). */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { COUNTRY_BN, REGION_BN } from "./bn.mjs";
import { DIVISIONS, NATIONAL } from "./divisions.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => fs.readFileSync(path.join(root, p), "utf8");
const exists = (p) => fs.existsSync(path.join(root, p));

const countries = JSON.parse(read(".cache/countries.json"));
const photos = exists(".cache/photos.json")
  ? JSON.parse(read(".cache/photos.json"))
  : {};
const flagsJs = read("geo-flags.js");
const flags = (() => {
  const m = flagsJs.match(/FLAG_CODES=(\[[\s\S]*?\]);/);
  return m ? JSON.parse(m[1]) : [];
})();

// Parse map-data.js files (var X = { ... };) to extract keys + labels
function parseLabelsMap(jsText, varName) {
  const start = jsText.indexOf(`var ${varName} = `) + `var ${varName} = `.length;
  const rest = jsText.slice(start);
  let depth = 0, end = -1;
  for (let i = 0; i < rest.length; i++) {
    if (rest[i] === "{") depth++;
    else if (rest[i] === "}") { depth--; if (depth === 0) { end = i + 1; break; } }
  }
  return end > 0 ? JSON.parse(rest.slice(0, end)) : {};
}
const bdLabels = parseLabelsMap(read("assets/bd-map-data.js"), "BD_LABELS");
const worldLabels = parseLabelsMap(read("assets/world-map-data.js"), "WORLD_LABELS");
const worldMapKeys = Object.keys(parseLabelsMap(read("assets/world-map-data.js"), "WORLD_MAP") || {});
const bdMapKeys = Object.keys(bdLabels);

// Regions
const regionCounts = {};
const regionOrder = ["Africa", "Americas", "Asia", "Europe", "Oceania"];
for (const c of countries.filter((x) => x.unMember)) {
  if (!regionCounts[c.region]) regionCounts[c.region] = 0;
  regionCounts[c.region]++;
}

// Build countries array
const unMembers = countries
  .filter((c) => c.unMember)
  .sort((a, b) => a.name.common.localeCompare(b.name.common))
  .map((c) => {
    const id = String(c.ccn3).padStart(3, "0");
    const bn = COUNTRY_BN[c.cca3] || [c.name.common, c.name.common, c.capital?.[0] || "", c.capital?.[0] || ""];
    const flagCode = c.cca2.toLowerCase();
    return {
      iso2: c.cca2,
      iso3: c.cca3,
      id,
      en: c.name.common,
      bn: bn[1],
      capitalEn: bn[2] || (c.capital && c.capital[0]) || "",
      capitalBn: bn[3] || "",
      region: c.region,
      regionBn: REGION_BN[c.region] || c.region,
      area: c.area || 0,
      latlng: c.latlng || [],
      flagCode,
      hasMap: worldMapKeys.includes(id),
    };
  });

const divisions = DIVISIONS.map((d) => ({
  ...d,
  photo: photos[d.id] || null,
}));

const geoData = `/* GENERATED by scripts/build-data.mjs — do not edit.
   Country data: mledoze/countries (ODbL) + curated Bangla names (Geo Buddy).
   Flag artwork: lipis/flag-icons (MIT). Division photos: Wikimedia Commons.
   Built: ${new Date().toISOString().split("T")[0]} */
export const GEO={
  version:"1.0.0",
  updated:"${new Date().toISOString().split("T")[0]}",
  national:${JSON.stringify(NATIONAL)},
  regions:${JSON.stringify(
    regionOrder.filter((r) => regionCounts[r]).map((r) => ({
      id: r.toLowerCase(),
      en: r,
      bn: REGION_BN[r] || r,
      count: regionCounts[r] || 0,
    }))
  )},
  countries:${JSON.stringify(unMembers)},
  divisions:${JSON.stringify(divisions, null, 0)},
  bdLabels:${JSON.stringify(bdLabels)},
  worldLabels:${JSON.stringify(worldLabels)},
  bdMapIds:${JSON.stringify(bdMapKeys)},
  worldMapIds:${JSON.stringify(worldMapKeys)},
};
`;

fs.writeFileSync(path.join(root, "geo-data.js"), geoData);
console.log(`geo-data.js: ${unMembers.length} countries, ${divisions.length} divisions, ${worldMapKeys.length} map paths`);
