/* Build orchestrator: runs the full data pipeline, generates sw.js cache manifest,
   and computes a version string from all source + asset hashes. */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { execSync } from "node:child_process";
import { createHash } from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const run = (cmd) => execSync(cmd, { cwd: ROOT, stdio: "inherit" });

/* ---- Run sub-tasks in order ---- */
console.log("\n=== fetch ===");
run("node scripts/fetch.mjs");
console.log("\n=== maps ===");
run("node scripts/maps.mjs");
console.log("\n=== flags ===");
run("node scripts/flags.mjs");
console.log("\n=== photos ===");
run("node scripts/photos.mjs");
console.log("\n=== icons ===");
run("node scripts/icons.mjs");
console.log("\n=== build-data ===");
run("node scripts/build-data.mjs");

/* ---- Collect precache file list ---- */
function walk(dir, base = "") {
  const out = [];
  for (const d of readdirSync(dir, { withFileTypes: true })) {
    const rel = base ? `${base}/${d.name}` : d.name;
    if (d.isDirectory()) out.push(...walk(path.join(dir, d.name), rel));
    else out.push("/" + rel);
  }
  return out;
}

const exists = (rel) => {
  try { readFileSync(path.join(ROOT, rel.startsWith("/") ? rel.slice(1) : rel)); return true; } catch { return false; }
};

const precacheFiles = [
  "/",
  "/index.html",
  "/src/engine.js",
  "/geo-data.js",
  "/geo-flags.js",
  "/manifest.json",
  "/assets/style.css",
  "/assets/bd-map.svg",
  "/assets/bd-map-data.js",
  "/assets/world-map.svg",
  "/assets/world-map-data.js",
  ...walk(path.join(ROOT, "assets", "icons"), "assets/icons").filter((f) => f.endsWith(".png")),
  ...walk(path.join(ROOT, "assets", "flags"), "assets/flags").filter((f) => f.endsWith(".svg")),
  ...walk(path.join(ROOT, "assets", "fonts"), "assets/fonts").filter((f) => f.endsWith(".woff2")),
].filter(exists);

/* ---- Compute version hash ---- */
const h = createHash("sha1");
for (const rel of precacheFiles) {
  const abs = path.join(ROOT, rel.startsWith("/") ? rel.slice(1) : rel);
  try { h.update(readFileSync(abs)); } catch {}
}
const version = h.digest("hex").slice(0, 8);
console.log("\nversion:", version);

/* ---- Generate sw.js ---- */
const swContent = `/* Service worker — DO NOT EDIT. Generated by build.mjs */
const CACHE = "geo-buddy-${version}";
const PRECACHE = ${JSON.stringify(precacheFiles)};

self.addEventListener("install", (e) => {
  e.waitUntil(
    caches.open(CACHE)
      .then((c) => c.addAll(PRECACHE))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys()
      .then((ks) => ks.filter((k) => k !== CACHE).map((k) => caches.delete(k)))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (e) => {
  if (e.request.method !== "GET") return;
  e.respondWith(
    caches.match(e.request).then((hit) => hit || fetch(e.request).then((res) => {
      if (!res.ok || res.type !== "basic") return res;
      const clone = res.clone();
      caches.open(CACHE).then((c) => c.put(e.request, clone));
      return res;
    }))
  );
});
`;
writeFileSync(path.join(ROOT, "sw.js"), swContent);
console.log(`wrote sw.js (${(swContent.length / 1024).toFixed(0)} KB)`);

/* ---- Generate manifest.json ---- */
const manifest = {
  name: "Geo Buddy",
  short_name: "GeoBuddy",
  description: "Bangladesh & world geography for kids (EN + BN)",
  start_url: "/",
  display: "standalone",
  background_color: "#0E3B2E",
  theme_color: "#0E3B2E",
  icons: [
    { src: "assets/icons/icon-192.png", sizes: "192x192", type: "image/png" },
    { src: "assets/icons/icon-512.png", sizes: "512x512", type: "image/png" },
    { src: "assets/icons/maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
  ],
};
writeFileSync(path.join(ROOT, "manifest.json"), JSON.stringify(manifest, null, 2) + "\n");
console.log("wrote manifest.json");

console.log("\n=== build done ===");