/* Copy flag-icons 4x3 SVGs (MIT) for every UN member into assets/flags/,
   minified, and emit geo-flags.js listing the available codes.

   We ship individual files rather than data-URIs so the quiz can lazy-load just
   the flag it is showing; the service worker precaches the whole set for offline. */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SRC = path.join(root, "node_modules", "flag-icons", "flags", "4x3");
const OUT = path.join(root, "assets", "flags");

const norm = (x) => x.replace(/\r?\n/g, "").trim();
const minify = (svg) =>
  norm(
    svg
      .replace(/<\?xml[^>]*\?>/g, "")
      .replace(/<!--[\s\S]*?-->/g, "")
      .replace(/>\s+</g, "><")
      .replace(/\s{2,}/g, " ")
  );

const countries = JSON.parse(
  fs.readFileSync(path.join(root, ".cache", "countries.json"), "utf8")
).filter((c) => c.unMember);

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });

const codes = [];
const missing = [];
for (const c of countries.sort((a, b) => a.cca2.localeCompare(b.cca2))) {
  const code = c.cca2.toLowerCase();
  const src = path.join(SRC, `${code}.svg`);
  if (!fs.existsSync(src)) {
    missing.push(code);
    continue;
  }
  fs.writeFileSync(path.join(OUT, `${code}.svg`), minify(fs.readFileSync(src, "utf8")));
  codes.push(code);
}

const banner = `/* GENERATED by scripts/flags.mjs — do not edit.
   Flag artwork: lipis/flag-icons (MIT). ${codes.length} UN-member flags. */\n`;
fs.writeFileSync(
  path.join(root, "geo-flags.js"),
  `${banner}export const FLAG_CODES=${JSON.stringify(codes)};\nexport const FLAG_BASE="assets/flags/";\nexport const flagUrl=(cc2)=>FLAG_BASE+String(cc2).toLowerCase()+".svg";\n`
);

console.log(`flags: ${codes.length} written to assets/flags/`);
if (missing.length) console.warn("missing flags:", missing.join(", "));
